### ISSUE TITLE
Laravel 7 Not Supported

### ISSUE THREAD

**Issue by aryno** [guilhermegonzaga/presenter#10]
Is this package still being maintained? It does not support laravel 7.

**Comment by guilhermegonzaga** [comment]
Hi, this package is maintained yes, for me, I am always following possible problems and corrections.
Have you identified any problems using Laravel 7?
I will take the time today to update the documentation and check if there are any problems with Laravel 7

**Comment by RaulCorreia** [comment]
has any progress been made in updating compatibility with laravel 7? I'm waiting anxiously

**Comment by guilhermegonzaga** [comment]
Changes made and the package now supports Laravel 7.
Thanks for reporting the problem and sorry for the delay in resolving.

Feel free to open PR with possible corrections or suggestions.
